<?php

/**
 * Implements hook_menu().
 */
function stemworks_events_menu() {
  $items = array();
    $items['stemworks_events/events'] = array(
        'title' => 'stemworks_events Events',
        'page callback' => 'stemworks_events_events',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );
  return $items;
}

function stemworks_events_events() {
$today = date("Y-m-d 23:59");

	
$query = new EntityFieldQuery();
$query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'events')
  ->propertyCondition('status', NODE_PUBLISHED)
  ->fieldCondition('field_event_unit', 'value', 'stemworks', '=')
  ->fieldCondition('field_event_date', 'value', $today, '>')
  ->fieldOrderBy('field_event_date', 'value', 'ASC')
  ->range(0,3)
  // Run the query as user 1.
  ->addMetaData('account', user_load(1));

$result = $query->execute();
if (isset($result['node'])) {
  $items_nids = array_keys($result['node']);
  $items = entity_load('node', $items_nids);
} 
	//print_r($items);
	//echo $now; exit;

foreach($items as $item){ 

$node = node_load($item->nid);
?>
		
		
<div class="col-md-4">

<h4><a href="https://library.gwu.edu/<?php print drupal_get_path_alias('node/' . $node->nid);?>"><?php print $node->title; ?></a></h4>

<div class="event-image"><img src="<?php print file_create_url($node->field_events_image[$node->language][0]['uri']); ?>" style="width: 100px;" alt=""></div>

<p><i><?php print date("l, F j, Y", strtotime($node->field_event_date[$node->language][0]['value'])); ?></i></p>

<div><?php print $node->body[$node->language][0]['safe_summary']; ?></div>

</div>	
		
		
		
<?php	}

}
